In [1]:
from Bio import Align
aligner = Align.PairwiseAligner()

In [2]:
aligner = Align.PairwiseAligner(match_score=1.0)

In [3]:
aligner.match_score = 1.0

In [4]:
target = "GAACT"
query = "GAT"
score = aligner.score(target, query)
score

3.0

In [5]:
alignments = aligner.align(target, query)
alignment = alignments[0]
alignment

<Alignment object (2 rows x 5 columns) at 0x110724a40>

In [6]:
for alignment in alignments:
    print(alignment)

target            0 GAACT 5
                  0 ||--| 5
query             0 GA--T 3

target            0 GAACT 5
                  0 |-|-| 5
query             0 G-A-T 3



In [7]:
alignment.score

3.0

In [8]:
alignment.target

'GAACT'

In [9]:
alignment.query

'GAT'

In [10]:
alignment = alignments[0]
alignment.coordinates

array([[0, 2, 4, 5],
       [0, 2, 2, 3]])

In [11]:
len(alignment)

2

In [12]:
alignment.length

5

In [13]:
alignment.aligned

array([[[0, 2],
        [4, 5]],

       [[0, 2],
        [2, 3]]])

In [14]:
alignment = alignments[1]
print(alignment)

target            0 GAACT 5
                  0 |-|-| 5
query             0 G-A-T 3



In [15]:
alignment.aligned

array([[[0, 1],
        [2, 3],
        [4, 5]],

       [[0, 1],
        [1, 2],
        [2, 3]]])

In [16]:
aligner.mode = "global"
aligner.mismatch_score = -10
alignments = aligner.align("AAACAAA", "AAAGAAA")
len(alignments)

2

In [17]:
print(alignments[0])

target            0 AAAC-AAA 7
                  0 |||--||| 8
query             0 AAA-GAAA 7



In [18]:
alignments[1].aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [19]:
print(alignments[1])

target            0 AAA-CAAA 7
                  0 |||--||| 8
query             0 AAAG-AAA 7



In [20]:
alignments[1].aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [21]:
aligner.mode = "local"
aligner.open_gap_score = -1
aligner.extend_gap_score = 0
chromosome = "AAAAAAAACCCCCCCAAAAAAAAAAAGGGGGGAAAAAAAA"
transcript = "CCCCCCCGGGGGG"
alignments1 = aligner.align(chromosome, transcript)
len(alignments1)

1

In [22]:
alignment1 = alignments1[0]
print(alignment1)

target            8 CCCCCCCAAAAAAAAAAAGGGGGG 32
                  0 |||||||-----------|||||| 24
query             0 CCCCCCC-----------GGGGGG 13



In [23]:
alignment1 = alignments1[0]
print(alignment1)

target            8 CCCCCCCAAAAAAAAAAAGGGGGG 32
                  0 |||||||-----------|||||| 24
query             0 CCCCCCC-----------GGGGGG 13



In [24]:
sequence = "CCCCGGGG"
alignments2 = aligner.align(transcript, sequence)
len(alignments2)

1

In [25]:
alignment2 = alignments2[0]
print(alignment2)

target            3 CCCCGGGG 11
                  0 ||||||||  8
query             0 CCCCGGGG  8



In [26]:
mapped_alignment = alignment1.map(alignment2)
print(mapped_alignment)

target           11 CCCCAAAAAAAAAAAGGGG 30
                  0 ||||-----------|||| 19
query             0 CCCC-----------GGGG  8



In [27]:
format(mapped_alignment, "psl")

'8\t0\t0\t0\t0\t0\t1\t11\t+\tquery\t8\t0\t8\ttarget\t40\t11\t30\t2\t4,4,\t0,4,\t11,26,\n'

In [28]:
from Bio.Seq import Seq
alignment1.target = Seq(None, len(alignment1.target))
alignment1.query = Seq(None, len(alignment1.query))
alignment2.target = Seq(None, len(alignment2.target))
alignment2.query = Seq(None, len(alignment2.query))
mapped_alignment = alignment1.map(alignment2)
format(mapped_alignment, "psl")

'8\t0\t0\t0\t0\t0\t1\t11\t+\tquery\t8\t0\t8\ttarget\t40\t11\t30\t2\t4,4,\t0,4,\t11,26,\n'

In [29]:
aligner.mode = "local"
target = "AGAACTC"
query = "GAACT"
score = aligner.score(target, query)
score

5.0

In [30]:
alignments = aligner.align(target, query)
for alignment in alignments:
    print(alignment)

target            1 GAACT 6
                  0 ||||| 5
query             0 GAACT 5



In [31]:
aligner.mode = "fogsaa"
aligner.mismatch_score = -10
alignments = aligner.align("AAACAAA", "AAAGAAA")
len(alignments)

/opt/anaconda3/lib/python3.12/site-packages/Bio/Align/__init__.py:3969: BiopythonWarning: One or more gap scores are greater than mismatch score. Algorithm may return incorrect results.
  score, paths = super().align(sA, sB, strand)


1

In [32]:
print(alignments[0])

target            0 AAAC-AAA 7
                  0 |||--||| 8
query             0 AAA-GAAA 7



In [33]:
from Bio import Align
aligner = Align.PairwiseAligner(match_score=1.0, mode="local")
print(aligner)

Pairwise sequence aligner with parameters
  wildcard: None
  match_score: 1.000000
  mismatch_score: 0.000000
  target_internal_open_gap_score: 0.000000
  target_internal_extend_gap_score: 0.000000
  target_left_open_gap_score: 0.000000
  target_left_extend_gap_score: 0.000000
  target_right_open_gap_score: 0.000000
  target_right_extend_gap_score: 0.000000
  query_internal_open_gap_score: 0.000000
  query_internal_extend_gap_score: 0.000000
  query_left_open_gap_score: 0.000000
  query_left_extend_gap_score: 0.000000
  query_right_open_gap_score: 0.000000
  query_right_extend_gap_score: 0.000000
  mode: local



In [34]:
aligner.algorithm

'Smith-Waterman'

In [35]:
aligner.epsilon

1e-06

In [36]:
from Bio import Align
aligner = Align.PairwiseAligner()
aligner.match_score

1.0

In [37]:
aligner.mismatch_score

0.0

In [38]:
score = aligner.score("ACGT", "ACAT")
print(score)

3.0


In [39]:
aligner.match_score = 1.0
aligner.mismatch_score = -2.0
aligner.gap_score = -2.5
score = aligner.score("ACGT", "ACAT")
print(score)

1.0


In [40]:
aligner.wildcard = "?"
score = aligner.score("ACGT", "AC?T")
print(score)

3.0


In [41]:
from Bio.Align import substitution_matrices
substitution_matrices.load()

['BENNER22',
 'BENNER6',
 'BENNER74',
 'BLASTN',
 'BLASTP',
 'BLOSUM45',
 'BLOSUM50',
 'BLOSUM62',
 'BLOSUM80',
 'BLOSUM90',
 'DAYHOFF',
 'FENG',
 'GENETIC',
 'GONNET1992',
 'HOXD70',
 'JOHNSON',
 'JONES',
 'LEVIN',
 'MCLACHLAN',
 'MDM78',
 'MEGABLAST',
 'NUC.4.4',
 'PAM250',
 'PAM30',
 'PAM70',
 'RAO',
 'RISLER',
 'SCHNEIDER',
 'STR',
 'TRANS']

In [42]:
matrix = substitution_matrices.load("BLOSUM62")
print(matrix)

#  Matrix made by matblas from blosum62.iij
#  * column uses minimum score
#  BLOSUM Clustered Scoring Matrix in 1/2 Bit Units
#  Blocks Database = /data/blocks_5.0/blocks.dat
#  Cluster Percentage: >= 62
#  Entropy =   0.6979, Expected =  -0.5209
     A    R    N    D    C    Q    E    G    H    I    L    K    M    F    P    S    T    W    Y    V    B    Z    X    *
A  4.0 -1.0 -2.0 -2.0  0.0 -1.0 -1.0  0.0 -2.0 -1.0 -1.0 -1.0 -1.0 -2.0 -1.0  1.0  0.0 -3.0 -2.0  0.0 -2.0 -1.0  0.0 -4.0
R -1.0  5.0  0.0 -2.0 -3.0  1.0  0.0 -2.0  0.0 -3.0 -2.0  2.0 -1.0 -3.0 -2.0 -1.0 -1.0 -3.0 -2.0 -3.0 -1.0  0.0 -1.0 -4.0
N -2.0  0.0  6.0  1.0 -3.0  0.0  0.0  0.0  1.0 -3.0 -3.0  0.0 -2.0 -3.0 -2.0  1.0  0.0 -4.0 -2.0 -3.0  3.0  0.0 -1.0 -4.0
D -2.0 -2.0  1.0  6.0 -3.0  0.0  2.0 -1.0 -1.0 -3.0 -4.0 -1.0 -3.0 -3.0 -1.0  0.0 -1.0 -4.0 -3.0 -3.0  4.0  1.0 -1.0 -4.0
C  0.0 -3.0 -3.0 -3.0  9.0 -3.0 -4.0 -3.0 -3.0 -1.0 -1.0 -3.0 -1.0 -2.0 -3.0 -1.0 -1.0 -2.0 -2.0 -1.0 -3.0 -3.0 -2.0 -4.0
Q -1.0  1.0  0.0  0.

In [43]:
aligner.substitution_matrix = matrix
score = aligner.score("ACDQ", "ACDQ")
score

24.0

In [44]:
score = aligner.score("ACDQ", "ACNQ")
score

19.0

In [45]:
matrix["D", "X"]

-1.0

In [46]:
score = aligner.score("ACDQ", "ACXQ")
score

17.0

In [47]:
from Bio import Align
aligner = Align.PairwiseAligner()
def my_gap_score_function(start, length):
    if start == 2:
        return -1000
    else:
        return -1 * length

aligner.query_gap_score = my_gap_score_function
alignments = aligner.align("AACTT", "AATT")
for alignment in alignments:
    print(alignment)

target            0 AACTT 5
                  0 -|.|| 5
query             0 -AATT 4

target            0 AACTT 5
                  0 |-.|| 5
query             0 A-ATT 4

target            0 AACTT 5
                  0 ||.-| 5
query             0 AAT-T 4

target            0 AACTT 5
                  0 ||.|- 5
query             0 AATT- 4



In [48]:
from Bio import Align
aligner = Align.PairwiseAligner(scoring="blastn")
print(aligner)

Pairwise sequence aligner with parameters
  substitution_matrix: <Array object at 0x111b3c6d0>
  target_internal_open_gap_score: -7.000000
  target_internal_extend_gap_score: -2.000000
  target_left_open_gap_score: -7.000000
  target_left_extend_gap_score: -2.000000
  target_right_open_gap_score: -7.000000
  target_right_extend_gap_score: -2.000000
  query_internal_open_gap_score: -7.000000
  query_internal_extend_gap_score: -2.000000
  query_left_open_gap_score: -7.000000
  query_left_extend_gap_score: -2.000000
  query_right_open_gap_score: -7.000000
  query_right_extend_gap_score: -2.000000
  mode: global



In [49]:
print(aligner.substitution_matrix[:, :])

     A    T    G    C    S    W    R    Y    K    M    B    V    H    D    N
A  2.0 -3.0 -3.0 -3.0 -3.0 -1.0 -1.0 -3.0 -3.0 -1.0 -3.0 -1.0 -1.0 -1.0 -2.0
T -3.0  2.0 -3.0 -3.0 -3.0 -1.0 -3.0 -1.0 -1.0 -3.0 -1.0 -3.0 -1.0 -1.0 -2.0
G -3.0 -3.0  2.0 -3.0 -1.0 -3.0 -1.0 -3.0 -1.0 -3.0 -1.0 -1.0 -3.0 -1.0 -2.0
C -3.0 -3.0 -3.0  2.0 -1.0 -3.0 -3.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -3.0 -2.0
S -3.0 -3.0 -1.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
W -1.0 -1.0 -3.0 -3.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
R -1.0 -3.0 -1.0 -3.0 -1.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
Y -3.0 -1.0 -3.0 -1.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
K -3.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -2.0
M -1.0 -3.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
B -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0
V -1.0 -3.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0 -2.0

In [50]:
from Bio import Align
aligner = Align.PairwiseAligner()
alignments = aligner.align("AAA", "AA")
len(alignments)

3

In [51]:
from Bio import Align
aligner = Align.PairwiseAligner()
alignments = aligner.align("AAA", "AA")
print(alignments[2])

target            0 AAA 3
                  0 -|| 3
query             0 -AA 2



In [52]:
print(alignments[0])

target            0 AAA 3
                  0 ||- 3
query             0 AA- 2



In [53]:
for alignment in alignments:
    print(alignment)

target            0 AAA 3
                  0 ||- 3
query             0 AA- 2

target            0 AAA 3
                  0 |-| 3
query             0 A-A 2

target            0 AAA 3
                  0 -|| 3
query             0 -AA 2



In [54]:
# alignments = list(alignments)
print(alignments.score)

2.0


In [55]:
from Bio import Align
from Bio.Seq import reverse_complement
target = "AAAACCC"
query = "AACC"
aligner = Align.PairwiseAligner()
aligner.mismatch_score = -1
aligner.internal_gap_score = -1
aligner.score(target, query)  # strand is "+" by default

4.0

In [56]:
aligner.score(target, reverse_complement(query), strand="-")

4.0

In [57]:
aligner.score(target, query, strand="-")

0.0

In [58]:
aligner.score(target, reverse_complement(query))

0.0

In [59]:
alignments = aligner.align(target, query)
len(alignments)

1

In [60]:
print(alignments[0])

target            0 AAAACCC 7
                  0 --||||- 7
query             0 --AACC- 4



In [61]:
print(alignments.score)

4.0


In [62]:
print(alignments[0].format("bed")) # alignments = list(alignments)

target	2	6	query	4	+	2	6	0	1	4,	0,



In [63]:
alignments = aligner.align(target, reverse_complement(query), strand="-")
len(alignments)

1

In [64]:
print(alignments[0])

target            0 AAAACCC 7
                  0 --||||- 7
query             4 --AACC- 0



In [65]:
print(alignments[0].format("bed")) # alignments = list(alignments)

target	2	6	query	4	-	2	6	0	1	4,	0,



In [66]:
alignments = aligner.align(target, query, strand="-")
len(alignments)

2

In [67]:
print(alignments[0])

target            0 AAAACCC----  7
                  0 ----------- 11
query             4 -------GGTT  0



In [68]:
print(alignments[1])

target            0 ----AAAACCC  7
                  0 ----------- 11
query             4 GGTT-------  0



In [69]:
aligner.left_gap_score = -0.5
aligner.right_gap_score = -0.2
aligner.score(target, query)

2.8

In [70]:
alignments = aligner.align(target, query)
len(alignments)

1

In [71]:
print(alignments[0])

target            0 AAAACCC 7
                  0 --||||- 7
query             0 --AACC- 4



In [72]:
aligner.score(target, reverse_complement(query), strand="-")

3.1

In [73]:
alignments = aligner.align(target, reverse_complement(query), strand="-")
len(alignments)

1

In [74]:
print(alignments[0])

target            0 AAAACCC 7
                  0 --||||- 7
query             4 --AACC- 0



In [75]:
from Bio.Align.substitution_matrices import Array
counts = Array("ACGT")
print(counts)

A 0.0
C 0.0
G 0.0
T 0.0



In [76]:
counts.alphabet

'ACGT'

In [77]:
counts["C"] = -3
counts[2] = 7
print(counts)

A  0.0
C -3.0
G  7.0
T  0.0



In [78]:
counts[1]

-3.0

In [79]:
from Bio.Align.substitution_matrices import Array
counts = Array("ACGT", dims=2)
print(counts)

    A   C   G   T
A 0.0 0.0 0.0 0.0
C 0.0 0.0 0.0 0.0
G 0.0 0.0 0.0 0.0
T 0.0 0.0 0.0 0.0



In [80]:
counts["A", "C"] = 12.0
counts[2, 1] = 5.0
counts[3, "T"] = -2
print(counts)

    A    C   G    T
A 0.0 12.0 0.0  0.0
C 0.0  0.0 0.0  0.0
G 0.0  5.0 0.0  0.0
T 0.0  0.0 0.0 -2.0



In [81]:
counts = Array("ACGT", dims=2)
counts["A", "C"] = 12.0
counts[2, 1] = 5.0
counts[3, "T"] = -2

In [82]:
counts["G"]

Array([0., 5., 0., 0.],
         alphabet='ACGT')

In [83]:
counts[:, "C"]

Array([12.,  0.,  5.,  0.],
         alphabet='ACGT')

In [84]:
import numpy as np
x = Array("ACGT")
x["C"] = 5

In [85]:
x

Array([0., 5., 0., 0.],
         alphabet='ACGT')

In [86]:
a = np.array(x)  # create a plain numpy array
a

array([0., 5., 0., 0.])

In [87]:
d = dict(x)  # create a plain dictionary
d

{'A': 0.0, 'C': 5.0, 'G': 0.0, 'T': 0.0}

In [88]:
a = Array("ABCD", dims=2, data=np.arange(16).reshape(4, 4))
print(a)

     A    B    C    D
A  0.0  1.0  2.0  3.0
B  4.0  5.0  6.0  7.0
C  8.0  9.0 10.0 11.0
D 12.0 13.0 14.0 15.0



In [89]:
b = a.select("CAD")
print(b)

     C    A    D
C 10.0  8.0 11.0
A  2.0  0.0  3.0
D 14.0 12.0 15.0



In [90]:
c = a.select("DEC")
print(c)

     D   E    C
D 15.0 0.0 14.0
E  0.0 0.0  0.0
C 11.0 0.0 10.0



In [91]:
from Bio import SeqIO

record = SeqIO.read("ecoli.fa", "fasta")  # kiçik fasta faylı ilə sına
print(record.id)
print(record.seq)

gi|545778205|gb|U00096.3|
AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTACAGGAAACACAGAAAAAAGCCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGCGAGTGTTGAAGTTCGGCGGTACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCTGGAAAGCAATGCCAGGCAGGGGCAGGTGGCCACCGTCCTCTCTGCCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTGAAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATCAGCGATGCCGAACGTATTTTTGCCGAACTTTTGACGGGACTCGCCGCCGCCCAGCCGGGGTTCCCGCTGGCGCAATTGAAAACTTTCGTCGATCAGGAATTTGCCCAAATAAAACATGTCCTGCATGGCATTAGTTTGTTGGGGCAGTGCCCGGATAGCATCAACGCTGCGCTGATTTGCCGTGGCGAGAAAATGTCGATCGCCATTATGGCCGGCGTATTAGAAGCGCGCGGTCACAACGTTACTGTTATCGATCCGGTCGAAAAACTGCTGGCAGTGGGGCATTACCTCGAATCTACCGTCGATATTGCTGAGTCCACCCGCCGTATTGCGGCAAGCCGCATTCCGGCTGATCACATGGTGCTGATGGCAGGTTTCACCGCCGGTAATGAAAAAGGCGAACTGGTGGTGCTTGGACGCAACGGTTCCGACTACTCTGCTGCGGT

In [92]:
from Bio.Align import PairwiseAligner
aligner = PairwiseAligner(scoring="blastn")
aligner.mode = "local"

In [93]:
from Bio import SeqIO
from Bio.Align import PairwiseAligner

aligner = PairwiseAligner()
aligner.mode = "global"  # və ya "global"

sequence1 = SeqIO.read("ecoli.fa", "fasta")
sequence2 = SeqIO.read("bsubtilis.fa", "fasta")

seq1 = sequence1.seq[:500]
seq2 = sequence2.seq[:500]

alignments = aligner.align(seq1, seq2)
print(alignments[0])


target            0 AG-CTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGT-GG-ATT--A-AAAAAAG
                  0 |--|||||--|-|-|---||---------|-|-|-|-|-|-|-|--||---|-|-----|
query             0 A-TCTTTT--T-C-G---GC---------T-T-T-T-T-T-TAG-TAT-CCACA-----G

target           54 AGTGTCTGATA-G-CAG-C-TTCTG--AAC-TGGTTACCTG--CC---GTGAGTA-AA--
                 60 ||-||-|-||--|-||--|-||-|---|-|-|--|-|||----||---|||-|-|-||--
query            30 AG-GT-T-AT-CGACA-ACATT-T-TCA-CAT--T-ACC--AACCCCTGTG-G-ACAAGG

target           99 TTAAAATTTT-A-----TTGA-C---TTA-GGTC--ACTAA-ATACT-TT-A-A-CCAAT
                120 ||----||||-|-----|||--|---||--|-|---|-|||-||--|-|--|-|-|||-|
query            75 TT----TTTTCAACAGGTTG-TCCGCTT-TG-T-GGA-TAAGAT--TGT-GACAACCA-T

target          141 ATAGGCATAGCG-CA-CAG---ACA----GA-TAAAAATTAC-A---GA-GT---ACACA
                180 -|-|-||-|||--|--|-|---|------|--||----|||--|---|--||---|-||-
query           122 -T-G-CA-AGC-TC-TC-GTTTA--TTTTG-GTA----TTA-TATTTG-TGTTTTA-AC-

target          183 ACAT

In [94]:
alignment = alignments[0]
aligned_seqA = alignment.target  # target (ecoli)
aligned_seqB = alignment.query   # query (bsubtilis)

# Aligned ardıcıllıqlar gap daxil olmaqla tam hizalanmış ardıcıllıqlardır
alignment_length = len(aligned_seqA)
print("Alignment length:", alignment_length)


Alignment length: 500


In [95]:
alignment = alignments[0]
substitutions = alignment.substitutions
print(substitutions)

     A    C    G    T
A 93.0  0.0  0.0  0.0
C  0.0 63.0  0.0  0.0
G  0.0  0.0 60.0  0.0
T  0.0  0.0  0.0 92.0



In [96]:
observed_frequencies = substitutions / substitutions.sum()
observed_frequencies = (observed_frequencies + observed_frequencies.transpose()) / 2.0
print(format(observed_frequencies, "%.4f"))

       A      C      G      T
A 0.3019 0.0000 0.0000 0.0000
C 0.0000 0.2045 0.0000 0.0000
G 0.0000 0.0000 0.1948 0.0000
T 0.0000 0.0000 0.0000 0.2987



In [97]:
background = observed_frequencies.sum(0)
print(format(background, "%.4f"))

A 0.3019
C 0.2045
G 0.1948
T 0.2987



In [98]:
expected_frequencies = background[:, None].dot(background[None, :])
print(format(expected_frequencies, "%.4f"))

       A      C      G      T
A 0.0912 0.0618 0.0588 0.0902
C 0.0618 0.0418 0.0398 0.0611
G 0.0588 0.0398 0.0379 0.0582
T 0.0902 0.0611 0.0582 0.0892



In [99]:
oddsratios = observed_frequencies / expected_frequencies
import numpy as np
scoring_matrix = np.log2(oddsratios)
print(scoring_matrix)

     A    C    G    T
A  1.7 -inf -inf -inf
C -inf  2.3 -inf -inf
G -inf -inf  2.4 -inf
T -inf -inf -inf  1.7



/opt/anaconda3/lib/python3.12/site-packages/Bio/Align/substitution_matrices/__init__.py:217: RuntimeWarning: divide by zero encountered in log2
  raw_results = super().__array_ufunc__(ufunc, method, *args, **kwargs)


In [100]:
aligner.substitution_matrix = scoring_matrix

In [101]:
from Bio import Align
filename = "protein.aln"
alignment = Align.read(filename, "clustal")

In [102]:
substitutions = alignment.substitutions

In [103]:
substitutions = substitutions.select("DEHKR")
print(substitutions)

       D      E      H      K      R
D 2360.0  270.0   15.0    1.0   48.0
E  241.0 3305.0   15.0   45.0    2.0
H    0.0   18.0 1235.0    8.0    0.0
K    0.0    9.0   24.0 3218.0  130.0
R    2.0    2.0   17.0  103.0 2079.0



In [104]:
observed_frequencies = substitutions / substitutions.sum()
observed_frequencies = (observed_frequencies + observed_frequencies.transpose()) / 2.0
print(format(observed_frequencies, "%.4f"))

       D      E      H      K      R
D 0.1795 0.0194 0.0006 0.0000 0.0019
E 0.0194 0.2514 0.0013 0.0021 0.0002
H 0.0006 0.0013 0.0939 0.0012 0.0006
K 0.0000 0.0021 0.0012 0.2448 0.0089
R 0.0019 0.0002 0.0006 0.0089 0.1581



In [105]:
background = observed_frequencies.sum(0)
print(format(background, "%.4f"))

D 0.2015
E 0.2743
H 0.0976
K 0.2569
R 0.1697



In [106]:
sum(background) == 1.0

True

In [107]:
expected_frequencies = background[:, None].dot(background[None, :])
print(format(expected_frequencies, "%.4f"))

       D      E      H      K      R
D 0.0406 0.0553 0.0197 0.0518 0.0342
E 0.0553 0.0752 0.0268 0.0705 0.0465
H 0.0197 0.0268 0.0095 0.0251 0.0166
K 0.0518 0.0705 0.0251 0.0660 0.0436
R 0.0342 0.0465 0.0166 0.0436 0.0288



In [108]:
import numpy as np
scoring_matrix = np.log2(observed_frequencies / expected_frequencies)
print(scoring_matrix)

      D    E    H     K    R
D   2.1 -1.5 -5.1 -10.4 -4.2
E  -1.5  1.7 -4.4  -5.1 -8.3
H  -5.1 -4.4  3.3  -4.4 -4.7
K -10.4 -5.1 -4.4   1.9 -2.3
R  -4.2 -8.3 -4.7  -2.3  2.5



In [109]:
from Bio.Align import PairwiseAligner
aligner = PairwiseAligner()
aligner.substitution_matrix = scoring_matrix
aligner.gap_score = -3.0
alignments = aligner.align("DEHEK", "DHHKK")
print(alignments[0])

target            0 DEHEK 5
                  0 |.|.| 5
query             0 DHHKK 5



In [110]:
print("%.2f" % alignments.score)

-2.18


In [111]:
score = (
    scoring_matrix["D", "D"]
    + scoring_matrix["E", "H"]
    + scoring_matrix["H", "H"]
    + scoring_matrix["E", "K"]
    + scoring_matrix["K", "K"]
)
print("%.2f" % score)

-2.18


In [112]:
from Bio.Align import substitution_matrices
with open("hg38.chrom.sizes") as handle:
    table = substitution_matrices.read(handle)

print(table)

chr1 248956422.0
chr2 242193529.0
chr3 198295559.0
chr4 190214555.0
chr5 181538259.0
chr6 170805979.0
chr7 159345973.0
chrX 156040895.0
chr8 145138636.0
chr9 138394717.0
chr11 135086622.0
chr10 133797422.0
chr12 133275309.0
chr13 114364328.0
chr14 107043718.0
chr15 101991189.0
chr16  90338345.0
chr17  83257441.0
chr18  80373285.0
chr20  64444167.0
chr19  58617616.0
chrY  57227415.0
chr22  50818468.0
chr21  46709983.0
chr15_KI270905v1_alt   5161414.0
chr6_GL000256v2_alt   4929269.0
chr6_GL000254v2_alt   4827813.0
chr6_GL000251v2_alt   4795265.0
chr6_GL000253v2_alt   4677643.0
chr6_GL000250v2_alt   4672374.0
chr6_GL000255v2_alt   4606388.0
chr6_GL000252v2_alt   4604811.0
chr17_KI270857v1_alt   2877074.0
chr16_KI270853v1_alt   2659700.0
chr16_KI270728v1_random   1872759.0
chr17_GL000258v2_alt   1821992.0
chr5_GL339449v2_alt   1612928.0
chr14_KI270847v1_alt   1511111.0
chr17_KI270908v1_alt   1423190.0
chr14_KI270846v1_alt   1351393.0
chr5_KI270897v1_alt   1144418.0
chr7_KI270803v1_alt   11

In [113]:
with open("hg38.chrom.sizes") as handle:
    table = substitution_matrices.read(handle, int)

print(table)

chr1 248956422
chr2 242193529
chr3 198295559
chr4 190214555
chr5 181538259
chr6 170805979
chr7 159345973
chrX 156040895
chr8 145138636
chr9 138394717
chr11 135086622
chr10 133797422
chr12 133275309
chr13 114364328
chr14 107043718
chr15 101991189
chr16  90338345
chr17  83257441
chr18  80373285
chr20  64444167
chr19  58617616
chrY  57227415
chr22  50818468
chr21  46709983
chr15_KI270905v1_alt   5161414
chr6_GL000256v2_alt   4929269
chr6_GL000254v2_alt   4827813
chr6_GL000251v2_alt   4795265
chr6_GL000253v2_alt   4677643
chr6_GL000250v2_alt   4672374
chr6_GL000255v2_alt   4606388
chr6_GL000252v2_alt   4604811
chr17_KI270857v1_alt   2877074
chr16_KI270853v1_alt   2659700
chr16_KI270728v1_random   1872759
chr17_GL000258v2_alt   1821992
chr5_GL339449v2_alt   1612928
chr14_KI270847v1_alt   1511111
chr17_KI270908v1_alt   1423190
chr14_KI270846v1_alt   1351393
chr5_KI270897v1_alt   1144418
chr7_KI270803v1_alt   1111570
chr19_GL949749v2_alt   1091841
chr19_KI270938v1_alt   1066800
chr19_GL949750

In [114]:
from Bio.Align import substitution_matrices

matrix = substitution_matrices.load("BLOSUM62")
print(matrix.alphabet)

ARNDCQEGHILKMFPSTWYVBZX*


In [115]:
print(matrix["A", "D"])

-2.0


In [116]:
matrix.header[0]

'Matrix made by matblas from blosum62.iij'

In [117]:
from Bio.Align import PairwiseAligner
aligner = PairwiseAligner()
aligner.substitution_matrix = matrix

In [118]:
text = str(matrix)
print(text)

#  Matrix made by matblas from blosum62.iij
#  * column uses minimum score
#  BLOSUM Clustered Scoring Matrix in 1/2 Bit Units
#  Blocks Database = /data/blocks_5.0/blocks.dat
#  Cluster Percentage: >= 62
#  Entropy =   0.6979, Expected =  -0.5209
     A    R    N    D    C    Q    E    G    H    I    L    K    M    F    P    S    T    W    Y    V    B    Z    X    *
A  4.0 -1.0 -2.0 -2.0  0.0 -1.0 -1.0  0.0 -2.0 -1.0 -1.0 -1.0 -1.0 -2.0 -1.0  1.0  0.0 -3.0 -2.0  0.0 -2.0 -1.0  0.0 -4.0
R -1.0  5.0  0.0 -2.0 -3.0  1.0  0.0 -2.0  0.0 -3.0 -2.0  2.0 -1.0 -3.0 -2.0 -1.0 -1.0 -3.0 -2.0 -3.0 -1.0  0.0 -1.0 -4.0
N -2.0  0.0  6.0  1.0 -3.0  0.0  0.0  0.0  1.0 -3.0 -3.0  0.0 -2.0 -3.0 -2.0  1.0  0.0 -4.0 -2.0 -3.0  3.0  0.0 -1.0 -4.0
D -2.0 -2.0  1.0  6.0 -3.0  0.0  2.0 -1.0 -1.0 -3.0 -4.0 -1.0 -3.0 -3.0 -1.0  0.0 -1.0 -4.0 -3.0 -3.0  4.0  1.0 -1.0 -4.0
C  0.0 -3.0 -3.0 -3.0  9.0 -3.0 -4.0 -3.0 -3.0 -1.0 -1.0 -3.0 -1.0 -2.0 -3.0 -1.0 -1.0 -2.0 -2.0 -1.0 -3.0 -3.0 -2.0 -4.0
Q -1.0  1.0  0.0  0.

In [119]:
from Bio.Align import substitution_matrices
m = substitution_matrices.load("BLOSUM62")

In [120]:
m.alphabet

'ARNDCQEGHILKMFPSTWYVBZX*'

In [121]:
substitution_matrices.load()

['BENNER22',
 'BENNER6',
 'BENNER74',
 'BLASTN',
 'BLASTP',
 'BLOSUM45',
 'BLOSUM50',
 'BLOSUM62',
 'BLOSUM80',
 'BLOSUM90',
 'DAYHOFF',
 'FENG',
 'GENETIC',
 'GONNET1992',
 'HOXD70',
 'JOHNSON',
 'JONES',
 'LEVIN',
 'MCLACHLAN',
 'MDM78',
 'MEGABLAST',
 'NUC.4.4',
 'PAM250',
 'PAM30',
 'PAM70',
 'RAO',
 'RISLER',
 'SCHNEIDER',
 'STR',
 'TRANS']

In [122]:
m = substitution_matrices.load("SCHNEIDER")
m.alphabet

('AAA',
 'AAC',
 'AAG',
 'AAT',
 'ACA',
 'ACC',
 'ACG',
 'ACT',
 'AGA',
 'AGC',
 'AGG',
 'AGT',
 'ATA',
 'ATC',
 'ATG',
 'ATT',
 'CAA',
 'CAC',
 'CAG',
 'CAT',
 'CCA',
 'CCC',
 'CCG',
 'CCT',
 'CGA',
 'CGC',
 'CGG',
 'CGT',
 'CTA',
 'CTC',
 'CTG',
 'CTT',
 'GAA',
 'GAC',
 'GAG',
 'GAT',
 'GCA',
 'GCC',
 'GCG',
 'GCT',
 'GGA',
 'GGC',
 'GGG',
 'GGT',
 'GTA',
 'GTC',
 'GTG',
 'GTT',
 'TAA',
 'TAC',
 'TAG',
 'TAT',
 'TCA',
 'TCC',
 'TCG',
 'TCT',
 'TGA',
 'TGC',
 'TGG',
 'TGT',
 'TTA',
 'TTC',
 'TTG',
 'TTT')

In [123]:
from Bio import Align
from Bio import SeqIO
seq1 = SeqIO.read("alpha.faa", "fasta")
seq2 = SeqIO.read("beta.faa", "fasta")
aligner = Align.PairwiseAligner()
score = aligner.score(seq1.seq, seq2.seq)
print(score)

72.0


In [124]:
alignments = aligner.align(seq1.seq, seq2.seq)

In [125]:
alignment = alignments[0]

In [126]:
print(alignment.score)

72.0


In [127]:
print(alignment)

target            0 MV-LS-PAD--KTN--VK-AA-WGKV-----GAHAGEYGAEALE-RMFLSF----P-TTK
                  0 ||-|--|----|----|--|--||||-----|---||--|--|--|--|------|-|--
query             0 MVHL-TP--EEK--SAV-TA-LWGKVNVDEVG---GE--A--L-GR--L--LVVYPWT--

target           41 TY--FPHF----DLSHGS---AQVK-G------HGKKV--A--DA-LTNAVAHV-DDMPN
                 60 ----|--|----|||------|-|--|------|||||--|--|--|--|--|--|---|
query            39 --QRF--FESFGDLS---TPDA-V-MGNPKVKAHGKKVLGAFSD-GL--A--H-LD---N

target           79 ALS----A-LSD-LHAH--KLR-VDPV-NFK-LLSHC---LLVT--LAAHLPA----EFT
                120 -|-----|-||--||----||--|||--||--||------|-|---||-|-------|||
query            81 -L-KGTFATLS-ELH--CDKL-HVDP-ENF-RLL---GNVL-V-CVLA-H---HFGKEFT

target          119 PA-VH-ASLDKFLAS---VSTV------LTS--KYR- 142
                180 |--|--|------|----|--|------|----||-- 217
query           124 P-PV-QA------A-YQKV--VAGVANAL--AHKY-H 147



In [128]:
from Bio import Align
from Bio import SeqIO
from Bio.Align import substitution_matrices
seq1 = SeqIO.read("alpha.faa", "fasta")
seq2 = SeqIO.read("beta.faa", "fasta")
aligner = Align.PairwiseAligner()
aligner.open_gap_score = -10
aligner.extend_gap_score = -0.5
aligner.substitution_matrix = substitution_matrices.load("BLOSUM62")
score = aligner.score(seq1.seq, seq2.seq)
print(score)

292.5


In [129]:
alignments = aligner.align(seq1.seq, seq2.seq)
len(alignments)

2

In [130]:
print(alignments[0].score)

292.5


In [131]:
print(alignments[0])

target            0 MV-LSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHF-DLS-----HGS
                  0 ||-|.|..|..|.|.||||--...|.|.|||.|.....|.|...|..|-|||-----.|.
query             0 MVHLTPEEKSAVTALWGKV--NVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGN

target           53 AQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAH
                 60 ..||.|||||..|.....||.|........||.||..||.|||.||.||...|...||.|
query            58 PKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHH

target          113 LPAEFTPAVHASLDKFLASVSTVLTSKYR 142
                120 ...||||.|.|...|..|.|...|..||. 149
query           118 FGKEFTPPVQAAYQKVVAGVANALAHKYH 147



In [132]:
aligner.mode = "local"
aligner.open_gap_score = -10
aligner.extend_gap_score = -1
alignments = aligner.align("LSPADKTNVKAA", "PEEKSAV")
print(len(alignments))

1


In [133]:
alignment = alignments[0]
print(alignment)

target            2 PADKTNV 9
                  0 |..|..| 7
query             0 PEEKSAV 7



In [134]:
print(alignment.score)

16.0


In [135]:
from Bio.Align import substitution_matrices
m = substitution_matrices.load("SCHNEIDER")
m.alphabet

('AAA',
 'AAC',
 'AAG',
 'AAT',
 'ACA',
 'ACC',
 'ACG',
 'ACT',
 'AGA',
 'AGC',
 'AGG',
 'AGT',
 'ATA',
 'ATC',
 'ATG',
 'ATT',
 'CAA',
 'CAC',
 'CAG',
 'CAT',
 'CCA',
 'CCC',
 'CCG',
 'CCT',
 'CGA',
 'CGC',
 'CGG',
 'CGT',
 'CTA',
 'CTC',
 'CTG',
 'CTT',
 'GAA',
 'GAC',
 'GAG',
 'GAT',
 'GCA',
 'GCC',
 'GCG',
 'GCT',
 'GGA',
 'GGC',
 'GGG',
 'GGT',
 'GTA',
 'GTC',
 'GTG',
 'GTT',
 'TAA',
 'TAC',
 'TAG',
 'TAT',
 'TCA',
 'TCC',
 'TCG',
 'TCT',
 'TGA',
 'TGC',
 'TGG',
 'TGT',
 'TTA',
 'TTC',
 'TTG',
 'TTT')

In [136]:
from Bio import Align
aligner = Align.PairwiseAligner()
aligner.substitution_matrix = m
aligner.gap_score = -1.0
s1 = ("AAT", "CTG", "TTT", "TTT")
s2 = ("AAT", "TTA", "TTT")
alignments = aligner.align(s1, s2)
len(alignments)

2

In [137]:
print(alignments[0])

AAT CTG TTT TTT
||| ... ||| ---
AAT TTA TTT ---



In [138]:
print(alignments[1])

AAT CTG TTT TTT
||| ... --- |||
AAT TTA --- TTT



In [139]:
print(m["CTG", "TTA"])

7.6


In [140]:
print(m["TTT", "TTA"])

-0.3


In [141]:
s1 = ("AAT", "CTG", "CTC", "TTT")
s2 = ("AAT", "TTA", "TTT")
alignments = aligner.align(s1, s2)
len(alignments)

1

In [142]:
print(alignments[0])

AAT CTG CTC TTT
||| ... --- |||
AAT TTA --- TTT



In [143]:
print(m["CTC", "TTA"])

6.5


In [144]:
s1 = ("Asn", "Leu", "Leu", "Phe")
s2 = ("Asn", "Leu", "Phe")

In [145]:
from Bio import Align
aligner = Align.PairwiseAligner()
aligner.alphabet = ['Ala', 'Arg', 'Asn', 'Asp', 'Cys',
                    'Gln', 'Glu', 'Gly', 'His', 'Ile',
                    'Leu', 'Lys', 'Met', 'Phe', 'Pro',
                    'Ser', 'Thr', 'Trp', 'Tyr', 'Val']  # fmt: skip


In [146]:
aligner.match = +6
aligner.mismatch = -1
alignments = aligner.align(s1, s2)
print(len(alignments))

2


In [147]:
print(alignments[0])

Asn Leu Leu Phe
||| ||| --- |||
Asn Leu --- Phe



In [148]:
print(alignments[1])

Asn Leu Leu Phe
||| --- ||| |||
Asn --- Leu Phe



In [149]:
print(alignments.score)

18.0


In [150]:
import numpy as np
from Bio import Align
aligner = Align.PairwiseAligner()
s1 = np.array([2, 10, 10, 13], np.int32)
s2 = np.array([2, 10, 13], np.int32)
aligner.match = +6
aligner.mismatch = -1
alignments = aligner.align(s1, s2)
print(len(alignments))

2


In [151]:
print(alignments[0])

2 10 10 13
| || -- ||
2 10 -- 13



In [152]:
print(alignments[1])

2 10 10 13
| -- || ||
2 -- 10 13



In [153]:
print(alignments.score)

18.0


In [154]:
aligner.wildcard = "?"
ord(aligner.wildcard)

63

In [155]:
s2 = np.array([2, 63, 13], np.int32)
aligner.gap_score = -3
alignments = aligner.align(s1, s2)
print(len(alignments))

2


In [156]:
print(alignments[0])

2 10 10 13
| .. -- ||
2 63 -- 13



In [157]:
print(alignments[1])

2 10 10 13
| -- .. ||
2 -- 63 13



In [158]:
print(alignments.score)

9.0


In [159]:
from Bio import Align
import numpy as np
aligner = Align.PairwiseAligner()
m = np.eye(5)
m[0, 1:] = m[1:, 0] = -2
m[2, 2] = 3
print(m)

[[ 1. -2. -2. -2. -2.]
 [-2.  1.  0.  0.  0.]
 [-2.  0.  3.  0.  0.]
 [-2.  0.  0.  1.  0.]
 [-2.  0.  0.  0.  1.]]


In [160]:
aligner.substitution_matrix = m
aligner.gap_score = -1
s1 = np.array([0, 2, 3, 4], np.int32)
s2 = np.array([0, 3, 2, 1], np.int32)
alignments = aligner.align(s1, s2)
print(len(alignments))

2


In [161]:
print(alignments[0])

0 - 2 3 4
| - | . -
0 3 2 1 -



In [162]:
print(alignments[1])

0 - 2 3 4
| - | - .
0 3 2 - 1



In [163]:
print(alignments.score)

2.0


In [164]:
from Bio import Align
aligner = Align.CodonAligner()

In [165]:
print(aligner)

Codon aligner with parameters
  wildcard: 'X'
  match_score: 1.0
  mismatch_score: 0.0
  frameshift_minus_two_score: -3.0
  frameshift_minus_one_score: -3.0
  frameshift_plus_one_score: -3.0
  frameshift_plus_two_score: -3.0



In [166]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
nuc1 = Seq("TCAGGGACTGCGAGAACCAAGCTACTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGTGGGGCGCTGGAG")
rna1 = SeqRecord(nuc1, id="rna1")
nuc2 = Seq("TCAGGGACTTCGAGAACCAAGCGCTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGTGGAGCACTGGAG")
rna2 = SeqRecord(nuc2, id="rna2")
aa1 = Seq("SGTARTKLLLLLAALCAAGGALE")
aa2 = Seq("SGTSRTKRLLLLAALGAAGGALE")
pro1 = SeqRecord(aa1, id="pro1")
pro2 = SeqRecord(aa2, id="pro2")

In [167]:
len(pro1)

23

In [168]:
len(pro2)

23

In [169]:
len(rna1)

69

In [170]:
len(rna2)

68

In [171]:
alignments1 = aligner.align(pro1, rna1)
len(alignments1)

1

In [172]:
alignment1 = next(alignments1)
print(alignment1)

pro1              0 S  G  T  A  R  T  K  L  L  L  L  L  A  A  L  C  A  A  G  G  
rna1              0 TCAGGGACTGCGAGAACCAAGCTACTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGTGGG

pro1             20 A  L  E   23
rna1             60 GCGCTGGAG 69



In [173]:
alignment1.coordinates

array([[ 0, 23],
       [ 0, 69]])

In [174]:
alignment1[0]

'SGTARTKLLLLLAALCAAGGALE'

In [175]:
alignment1[1]

'TCAGGGACTGCGAGAACCAAGCTACTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGTGGGGCGCTGGAG'

In [176]:
alignments2 = aligner.align(pro2, rna2)
len(alignments2)

1

In [177]:
alignment2 = next(alignments2)
print(alignment2)

pro2              0 S  G  T  S  R  T  K  R   8
rna2              0 TCAGGGACTTCGAGAACCAAGCGC 24

pro2              8 L  L  L  L  A  A  L  G  A  A  G  G  A  L  E   23
rna2             23 CTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGTGGAGCACTGGAG 68



In [178]:
alignment2[0]

'SGTSRTKRLLLLAALGAAGGALE'

In [179]:
alignment2[1]

'TCAGGGACTTCGAGAACCAAGCGCCTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGTGGAGCACTGGAG'

In [180]:
alignment2.coordinates

array([[ 0,  8,  8, 23],
       [ 0, 24, 23, 68]])

In [181]:
from Bio.Seq import translate
len(nuc2)

68

In [182]:
len(alignment2[1])

69

In [183]:
translate(alignment2[1])

'SGTSRTKRLLLLAALGAAGGALE'

In [184]:
_ == aa2

True

In [185]:
alignments1.score

23.0

In [186]:
alignment1.score

23.0

In [187]:
alignments2.score

20.0

In [188]:
alignment2.score

20.0

In [189]:
score = aligner.score(pro1, rna1)
print(score)

23.0


In [190]:
score = aligner.score(pro2, rna2)
print(score)

20.0


In [191]:
aa3 = Seq("MGTALLLLLAALCAAGGALE")
pro3 = SeqRecord(aa3, id="pro3")
nuc3 = Seq("ATGGGAACCGCGCTGCTTTTGCTACTGGCCGCGCTCTGCGCCGCAGGTGGGGCCCTGGAG")
rna3 = SeqRecord(nuc3, id="rna3")
nuc3.translate() == aa3

True

In [192]:
alignments3 = aligner.align(pro3, rna3)
len(alignments3)

1

In [193]:
alignment3 = next(alignments3)
print(alignment3)

pro3              0 M  G  T  A  L  L  L  L  L  A  A  L  C  A  A  G  G  A  L  E  
rna3              0 ATGGGAACCGCGCTGCTTTTGCTACTGGCCGCGCTCTGCGCCGCAGGTGGGGCCCTGGAG

pro3             20 
rna3             60 



In [194]:
import numpy as np
from Bio.Align import Alignment
sequences = [pro1, pro2, pro3]
protein_alignment = Alignment(
    sequences, coordinates=np.array([[0, 4, 7, 23], [0, 4, 7, 23], [0, 4, 4, 20]])
)
print(protein_alignment)

pro1              0 SGTARTKLLLLLAALCAAGGALE 23
pro2              0 SGTSRTKRLLLLAALGAAGGALE 23
pro3              0 MGTA---LLLLLAALCAAGGALE 20



In [195]:
codon_alignment = protein_alignment.mapall([alignment1, alignment2, alignment3])
print(codon_alignment)

rna1              0 TCAGGGACTGCGAGAACCAAGCTA 24
rna2              0 TCAGGGACTTCGAGAACCAAGCGC 24
rna3              0 ATGGGAACCGCG---------CTG 15

rna1             24 CTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGTGGGGCGCTGGAG 69
rna2             23 CTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGTGGAGCACTGGAG 68
rna3             15 CTTTTGCTACTGGCCGCGCTCTGCGCCGCAGGTGGGGCCCTGGAG 60



In [196]:
from Bio.Align import analysis
pairwise_codon_alignment = codon_alignment[:2]
print(pairwise_codon_alignment)

rna1              0 TCAGGGACTGCGAGAACCAAGCTA 24
                  0 |||||||||.||||||||||||..
rna2              0 TCAGGGACTTCGAGAACCAAGCGC 24

rna1             24 CTGCTGCTGCTGGCTGCGCTCTGCGCCGCAGGTGGGGCGCTGGAG 69
                 24 ||.||||||||||||||||||.|||||||||||||.||.|||||| 69
rna2             23 CTCCTGCTGCTGGCTGCGCTCGGCGCCGCAGGTGGAGCACTGGAG 68



In [197]:
dN, dS = analysis.calculate_dn_ds(pairwise_codon_alignment, method="NG86")
print(dN, dS)

0.06771513500407537 0.20119798994600957


In [198]:
dN, dS = analysis.calculate_dn_ds(pairwise_codon_alignment, method="LWL85")
print(dN, dS)

0.06872849189292052 0.20755111805465212


In [199]:
dN, dS = analysis.calculate_dn_ds(pairwise_codon_alignment, method="YN00")
print(dN, dS)

0.08146882335838317 0.1277062092854794


In [200]:
dN, dS = analysis.calculate_dn_ds(pairwise_codon_alignment, method="ML")
print(dN, dS)

0.0694755813603418 0.20575445139267218


In [201]:
dN, dS = analysis.calculate_dn_ds_matrix(codon_alignment, method="NG86")
print(dN)

rna1    0.000000
rna2    0.067715    0.000000
rna3    0.060204    0.145469    0.000000
    rna1    rna2    rna3


In [202]:
print(dS)

rna1    0.000000
rna2    0.201198    0.000000
rna3    0.664268    0.798957    0.000000
    rna1    rna2    rna3


In [203]:
print(dN)

rna1    0.000000
rna2    0.067715    0.000000
rna3    0.060204    0.145469    0.000000
    rna1    rna2    rna3


In [204]:
from Bio.Phylo.TreeConstruction import DistanceTreeConstructor
dn_constructor = DistanceTreeConstructor()
ds_constructor = DistanceTreeConstructor()
dn_tree = dn_constructor.upgma(dN)
ds_tree = ds_constructor.upgma(dS)
print(type(dn_tree))

<class 'Bio.Phylo.BaseTree.Tree'>


In [205]:
print(dn_tree)

Tree(rooted=True)
    Clade(branch_length=0, name='Inner2')
        Clade(branch_length=0.05329614516492466, name='rna2')
        Clade(branch_length=0.023194031750005527, name='Inner1')
            Clade(branch_length=0.030102113414919134, name='rna3')
            Clade(branch_length=0.030102113414919134, name='rna1')


In [206]:
print(ds_tree)

Tree(rooted=True)
    Clade(branch_length=0, name='Inner2')
        Clade(branch_length=0.36580615496736674, name='rna3')
        Clade(branch_length=0.26520715999436195, name='Inner1')
            Clade(branch_length=0.10059899497300478, name='rna2')
            Clade(branch_length=0.10059899497300478, name='rna1')


In [207]:
from Bio import SeqIO
from Bio import Align
from Bio.Align import CodonAligner
from Bio.Align.analysis import mktest
aligner = CodonAligner()
nucleotide_records = SeqIO.index("drosophila.fasta", "fasta")
for nucleotide_record in nucleotide_records.values():
    print(nucleotide_record.description)  


gi|9097|emb|X57361.1| Drosophila simulans (individual c) Adh gene for alcohol dehydrogenase
gi|9099|emb|X57362.1| Drosophila simulans (individual d) Adh gene for alcohol dehydrogenase
gi|9101|emb|X57363.1| Drosophila simulans (individual e) Adh gene for alcohol dehydrogenase
gi|9103|emb|X57364.1| Drosophila simulans (individual f) Adh gene for alcohol dehydrogenase
gi|9217|emb|X57365.1| Drosophila yakuba (individual a) Adh gene for alcohol dehydrogenase
gi|9219|emb|X57366.1| Drosophila yakuba (individual b) ADH gene for alcohol dehydrogenase
gi|9221|emb|X57367.1| Drosophila yakuba (individual c) Adh gene for alcohol dehydrogenase
gi|9223|emb|X57368.1| Drosophila yakuba (individual d) Adh gene for alcohol dehydrogenase
gi|9225|emb|X57369.1| Drosophila yakuba (individual e) Adh gene for alcohol dehydrogenase
gi|9227|emb|X57370.1| Drosophila yakuba (individual f) Adh gene for alcohol dehydrogenase
gi|9229|emb|X57371.1| Drosophila yakuba (individual g) Adh gene for alcohol dehydrogenase
gi

In [208]:
protein_alignment = Align.read("adh.aln", "clustal")
len(protein_alignment)

27

In [209]:
print(protein_alignment)

gi|9217|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9219|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9221|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9223|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9225|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9227|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9229|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9231|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9233|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9235|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9237|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9239|e         0 MAFTLTNKNVVFVAGLGGIGLDTSKELVKRDLKNLVILDRIENPAAIAELKAINPKVTVT
gi|9097|e         0 MAFTLTNK

In [210]:
codon_alignments = []
for protein_record in protein_alignment.sequences:
    nucleotide_record = nucleotide_records[protein_record.id]
    alignments = aligner.align(protein_record, nucleotide_record)
    assert len(alignments) == 1
    codon_alignment = next(alignments)
    codon_alignments.append(codon_alignment)

print(codon_alignment) 

gi|156859         0 M  S  F  T  L  T  N  K  N  V  I  F  V  A  G  L  G  G  I  G  
gi|156859         0 ATGTCGTTTACTTTGACCAACAAGAACGTGATTTTCGTTGCCGGTCTGGGAGGCATTGGT

gi|156859        20 L  D  T  S  K  E  L  L  K  R  D  L  K  N  L  V  I  L  D  R  
gi|156859        60 CTGGACACCAGCAAGGAGCTGCTCAAGCGCGATCTGAAGAACCTGGTGATCCTCGACCGC

gi|156859        40 I  E  N  P  A  A  I  A  E  L  K  A  I  N  P  K  V  T  V  T  
gi|156859       120 ATTGAGAACCCGGCTGCCATTGCCGAGCTGAAGGCAATCAATCCAAAGGTGACCGTCACC

gi|156859        60 F  Y  P  Y  D  V  T  V  P  I  A  E  T  T  K  L  L  K  T  I  
gi|156859       180 TTCTACCCCTATGATGTGACCGTGCCCATTGCCGAGACCACCAAGTTGCTGAAGACCATC

gi|156859        80 F  A  Q  L  K  T  V  D  V  L  I  N  G  A  G  I  L  D  D  H  
gi|156859       240 TTCGCCCAGCTGAAGACCGTCGATGTCCTGATCAACGGAGCTGGTATCCTGGACGATCAC

gi|156859       100 Q  I  E  R  T  I  A  V  N  Y  T  G  L  V  N  T  T  T  A  I  
gi|156859       300 CAGATCGAGCGCACCATTGCCGTCAACTACACTGGCCTGGTCAACACCACGACGGCCATT

gi|156859       120 L 

In [211]:
nucleotide_records.close()  # Close indexed FASTA file
alignment = protein_alignment.mapall(codon_alignments)
print(alignment)

gi|9217|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9219|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9221|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9223|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9225|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9227|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9229|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9231|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9233|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9235|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9237|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9239|e         0 ATGGCGTTTACCTTGACCAACAAGAACGTGGTTTTCGTGGCCGGTCTGGGAGGCATTGGT
gi|9097|e         0 ATGGCGTT

In [212]:
unique_species = ["Drosophila simulans", "Drosophila yakuba", "D.melanogaster"]
species = []
for record in alignment.sequences:
    description = record.description
    for s in unique_species:
        if s in description:
            break
    else:
        raise Exception(f"Failed to find species for {description}")
    species.append(s)

print(species)

['Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila yakuba', 'Drosophila simulans', 'Drosophila simulans', 'Drosophila simulans', 'Drosophila simulans', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster', 'D.melanogaster']


In [213]:
pvalue = mktest(alignment, species)
print(pvalue)

0.0020645725725430097
